name: tree
description: Education app with a mentor capability

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.0.0
  cloud_firestore: ^0.13.3
  firebase_auth: ^0.15.2
  provider: ^3.2.0
  google_sign_in: ^4.1.1
  shared_preferences: ^0.5.6+3
  random_string: ^2.0.1
  cupertino_icons: ^0.1.3
  flutter_spinkit: ^4.1.2
  google_fonts: ^1.1.0
  youtube_player_flutter: ^7.0.0+7
  flutter_plugin_pdf_viewer: ^1.0.7
  file_picker: ^1.13.0+1
  firebase_storage: ^3.1.6
  firebase_database: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - images/

  uses-material-design: true

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
